# Generated by Django 4.1 on 2023-12-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="replied",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
