# Generated by Django 4.1 on 2023-12-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_groupchat_group_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupchat",
            name="group_id",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
