# Generated by Django 4.1 on 2023-12-21 17:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_messages_image_alter_messages_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="image",
            field=models.ImageField(
                blank=True,
                default="",
                null=True,
                upload_to=api.models.upload_image_path,
            ),
        ),
    ]
