# Generated by Django 4.1 on 2024-08-13 14:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_messages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_group_image_path),
        ),
    ]
